- name: test filters
  hosts: localhost
  vars:
    mylist:
      - 1
      - 3 == 3
      - True
    myotherlist:
      - False
      - True
  tasks:
  - name: msg all are true 
    debug: msg="all are true!"
    when:  mylist is all

  - name: at least one is true 
    debug: msg="at least one is true"
    when: myotherlist is any
        
    