aws_ec2_key_name: "key-ansible-workshop"
aws_key_path: "/home/userforpython47/epam-devops-automation-tools/ansible-projects/aws_ssh_ed25519.priv"
aws_ec2_ami_filter: 
  description: "Amazon Linux 2023 AMI*"
  state: "available"

aws_ec2_tags:
  Name: "ec2-anszible-workshop"

aws_ec2_instance_type: "t2.micro"
aws_ec2_instance_count: 4
aws_ec2_instance_public_ip: yes
aws_ec2_instance_wait: yes
aws_ec2_instance_wait_timeout: 500
aws_ec2_instance_volumes:
  - device_name: /dev/sdb
    ebs:
      delete_on_termination: true
      volume_type: gp3
      volume_size: 10
  - device_name: /dev/sdc
    ebs:
      volume_type: gp3
      volume_size: 20
      delete_on_termination: true