---
# Main task file for provisioning an ec2
- name: Provision EC2
  include_tasks: "{{ item }}"
  loop:
    - ec2-ami.yml
    - ec2-key.yml
    - ec2-sg.yml
    - ec2-instace.yml
  when: aws_workshop_destroy is false