---
# Gather info vpc resources
- name: Gather VPC Info
  amazon.aws.ec2_vpc_net_info:
    filters:
      "tag:Name": "{{ aws_vpc_name }}"
  register: aws_vpc_info

# Destroy EC2 resources
- name: Gather EC2 Instance Info
  amazon.aws.ec2_instance_info:
    filters:
      "tag:Name": "{{ aws_ec2_tags.Name }}"
      instance-state-name: [ "running"]
  register: aws_ec2_instance_info

- name: Terminate EC2 Instance
  amazon.aws.ec2_instance:
    state: absent
    instance_ids: "{{ item.instance_id }}"
    wait: yes
  loop: "{{ aws_ec2_instance_info.instances }}"
  loop_control:
    label: "{{ item.instance_id }}"

- name: Remove an EC2 Key Pair
  amazon.aws.ec2_key:
    name: "{{ aws_ec2_key_name }}"
    state: absent
  
# Destroy SG resources
- name: Gather EC2 SG Info
  amazon.aws.ec2_group_info:
    filters:
      vpc-id: "{{ aws_vpc_info.vpcs.0.id }}"
  register: aws_ec2_sg_info

- name: Exclude Ec2 Default SG
  set_fact:
    aws_ec2_sg_list: "{{ aws_ec2_sg_info.security_groups | selectattr('group_name', 'match', 'default-.*') }}"

- name: Remove an EC2 SG
  ec2_group:
    group_id: "{{ item.group_id }}"
    state: absent
  loop: "{{ aws_ec2_sg_list }}"

# Destroy vpc resources

- name: Remove a VPC Subnet
  amazon.aws.ec2_vpc_subnet:
    state: absent
    vpc_id: "{{ aws_vpc_info.vpcs.0.id }}"
    cidr: "{{ aws_subnet_cidr_block }}"

- name: Gather route tables in VPC
  amazon.aws.ec2_vpc_route_table_info:
    filters:
      vpc-id: "{{ aws_vpc_info.vpcs.0.id }}"
      #association.main: false
  register: vpc_route_tables
    
- name: Remove all non-main route tables
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{ aws_vpc_info.vpcs.0.id }}"
    lookup: id
    route_table_id: "{{ item.route_table_id }}"
    state: absent
  loop: "{{ vpc_route_tables.route_tables }}"
  loop_control: 
    label: "{ item.route_table_id }"
  when: item.associations is undefined or item.associations.main is false

- name: Remove a VPC Internet Gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{ aws_vpc_info.vpcs.0.id }}"
    state: absent

- name: Remove a VPC
  amazon.aws.ec2_vpc_net:
    name: "{{ aws_vpc_name }}"
    cidr_block: "{{ aws_vpc_cidr_block }}"
    state: absent


